- name: make this server a dank selfhosting machine
  hosts: local
  vars_files:
    - vars.yml
  roles:
    - { role: base,    tags: ['base']    }
    - { role: httpd,   tags: ['httpd']   }
    - { role: acme,    tags: ['acme']    }
    - { role: nsd,     tags: ['nsd']     }
    - { role: smtpd,   tags: ['smtpd']   }
    - { role: spamd,   tags: ['spamd']   }
    - { role: prosody, tags: ['prosody'] }
    - { role: znc,     tags: ['znc']     }
